export enum ErrorCodeEnum {
  /* ========= USERS ========= */
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_NOT_VERIFIED = 'USER_NOT_VERIFIED',
  USER_WAS_REVOKED = 'USER_WAS_REVOKED',
  USER_NOT_MATCHED = 'USER_NOT_MATCHED',
  USER_WAS_CONNECTING_TO_PLATFORM = 'USER_WAS_CONNECTING_TO_PLATFORM',

  /* ========= NOTIFICATIONS ========= */
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_ID_REQUIRED = 'NOTIFICATION_ID_REQUIRED',
  NOTIFICATION_NOT_RETRYABLE = 'NOTIFICATION_NOT_RETRYABLE',
  NOTIFICATION_EMPTY_PAYLOAD = 'NOTIFICATION_EMPTY_PAYLOAD',
  NOTIFICATION_WAS_RECEIVED = 'NOTIFICATION_WAS_RECEIVED',

  /* ========= SERVICE EXCEPTIONS ========= */
  SERVICE_TIMEOUT = 'SERVICE_TIMEOUT',
  SERVICE_BAD_REQUEST = 'SERVICE_BAD_REQUEST',

  /* ========= IDENTITY EXCEPTIONS ========= */
  IDENTITY_ACCOUNT_NOT_CONNECTED = 'ACCOUNT_NOT_CONNECTED',

  /* ========= GENERAL ========= */
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  TOO_MANY_ATTEMPTS = 'TOO_MANY_ATTEMPTS',
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',
  NOT_ALLOWED = 'NOT_ALLOWED',
}
